name: Deploy Jekyll Site

on:
  push:
    branches:
      - master  # masterブランチにプッシュされたときに実行

  repository_dispatch:
    types: [microcms-update]  # microCMS の Webhook で実行

  workflow_dispatch: # 手動実行も可能

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Fetch microCMS data
        run: bundle exec ruby ./_plugins/microcms.rb  # microCMSからデータ取得
        env:
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site # Jekyllの出力ディレクトリ

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
