name: RuboCop

on: 
  push:
    paths:
      - "_plugins/**"
  pull_request:
    paths:
      - "_plugins/**"

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop -c ./.rubocop.yml
